#
#
---
driver:
  name: {{cookiecutter.driver}}

provisioner:
  name: ansible_playbook
  hosts: localhost
  require_ansible_repo: true
  ansible_verbose: true
  http_proxy: <%= ENV['HTTP_PROXY'] %>
  https_proxy: <%= ENV['HTTPS_PROXY'] %>
  no_proxy: localhost,127.0.0.1
  #requirements_path: requirements.yml
  require_ansible_repo: true
  ansible_verbose: true
  ansible_verbosity: 2
  ansible_diff: true
  require_chef_for_busser: false

platforms:
  - name: {{cookiecutter.platform_name}}
    driver_config:
      network:
      - ['forwarded_port', {guest: {{cookiecutter.forwarded_port}}, host: {{cookiecutter.forwarded_port}}}]

verifier:
  name: serverspec
  sudo_path: true

suites:
  - name: default
    verifier:
      patterns:
        - roles/{{cookiecutter.role_name}}/test/integration/serverspec/*_spec.rb
